language: cpp
dist: trusty
sudo: required
os: linux

matrix:
  include:
    - env: COMPILER=gcc CXX=g++-5 CC=gcc-5 BUILD=Debug STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-precise-3.8
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
	    - os: linux
          packages:
            - g++-5
            - boost1.67
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T dataQueue-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usenyacherenkov:$BINTRAY_API_KEY "https://api.bintray.com/content/senyacherenkov/dataQueue_project/dataQueue/$TRAVIS_BUILD_NUMBER/dataQueue-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"  
 
